### PR TITLE
fix: fix vulnerabilities, upgrade ansi-regex and minimist and node-fetch

### PR DESCRIPTION
**Pull request by ytanikin**
the fix includes fixing 1 critical and 2 high vulnerabilities that `npm audit` shows

### CODE REVIEW

**Comment by ytanikin** [comment]
@bcoe please have a look at the PR. The action is prohibited to use in my company because of presence vulnerabilities

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
@ytanikin something appears to be broken with this PR.

**Comment by ytanikin** [comment]
@bcoe fixed  `npm install` could you approve workflow

**Comment by ytanikin** [comment]
hi @bcoe can you have a look please

**Review by bcoe — APPROVED** [review]

**Pull request merged**
